### ISSUE TITLE
Nest.js example

### ISSUE THREAD

**Issue by ruciu** [swc-project/jest#4] opened 2020-11-11 13:26 UTC
Hi,

I tried to use swc-jest instead of ts-jest in clean Nest.js project. I used @swc-node/register to run app and it works like a charm. Then I tried to run jest and it produces error:

`error: Unexpected token `@`. Expected this, import, async, function, [ for array literal, { for object literal, @ for decorator, function, class, null, true, false, number, bigint, string, regexp, for template literal, (, or an identifier`
` --> /home/brutkowski/WebstormProjects/nest-swc/src/app.module.ts:5:1`

` Test suite failed to run `
` GenericFailure: failed to process js file `
` Caused by:  failed to parse module`
`at Compiler.transformSync (../node_modules/@swc/core/index.js:116:25) `
`at Object.transformSync (../node_modules/@swc/core/index.js:196:21)`
`at Object.process (../node_modules/@swc/jest/index.js:21:27)`
`at ScriptTransformer.transformSource (../node_modules/@jest/transform/build/ScriptTransformer.js:464:35)`
` at ScriptTransformer._transformAndBuildScript (../node_modules/@jest/transform/build/ScriptTransformer.js:569:40)`
`at ScriptTransformer.transform (../node_modules/@jest/transform/build/ScriptTransformer.js:607:25)`

I have created repository with complete reproduction at https://github.com/ruciu/nest-swc 
To run test execute yarn run test:e2e.

Could you please tell me what should I do?

Thank you

**Comment by kdy1** [comment] 2020-11-12 08:04
I guess you have to enable decorators.

See: https://swc.rs/docs/configuring-swc#jscparser

**Comment by ruciu** [comment] 2020-11-12 10:29
I have added .swcrc with
`
{
  "jsc": { 
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    }
  }
}`

and now I'm getting : Cannot find module 'regenerator-runtime' from 'app.e2e-spec.ts'

**Comment by kdy1** [comment] 2020-11-12 10:39
You need to do `npm i regenerator-runtime` or `yarn add regenerator-runtime`.

**Comment by ruciu** [comment] 2020-11-12 18:33
I installed it and now it's
` ✕ / (GET) (175 ms)`
`  ● AppController (e2e) › / (GET)`
`  TypeError: request is not a function`

or
`    ✕ / (GET) (173 ms)`
`  ● AppController (e2e) › / (GET)`
`    expected 200 "OK", got 500 "Internal Server Error"`
`[Nest] 13129   - 11/12/2020, 7:30:21 PM   [ExceptionHandler] Cannot read property 'getHello' of undefined`
`TypeError: Cannot read property 'getHello' of undefined`

when I change `import * as request from 'supertest';` to `import request from 'supertest';`.

**Comment by kdy1** [comment] 2020-11-23 12:28
Oh... Sorry for late response. I missed the mail.
I'll try to fix it soon.

**Comment by jays1204** [comment] 2021-07-21 05:45
@kdy1 stil not fixed?

**Comment by kdy1** [comment] 2021-07-21 05:48
I read it again and I found that you didn't specify `module` config.
It will work if you use proper module config.

**Comment by jays1204** [comment] 2021-07-21 07:04
@kdy1 I add module config. 
below is my full .swcrc.

```
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true,
      "dynamicImport": false
    },
    "target": "es2017"
  },
  "module": {
    "type": "commonjs",
    "noInterop": true
  }
}

```

I add module config with commonjs type because of wildcard import ` import * as request from 'supertest';`

But still error occurred. `   TypeError: request is not a function `.

commonjs type support wildcard import?

**Comment by kdy1** [comment] 2021-07-21 07:05
`noInterop: true` seems problematic to me. It should be false for many modules.

**Comment by jays1204** [comment] 2021-07-21 07:07
@kdy1 So I changed it. `noInterop: false`. But still same error. 

I am using below swc version.
```
    "@swc/cli": "^0.1.27",
    "@swc/core": "^1.2.38",
```

**Comment by kdy1** [comment] 2021-07-21 07:24
Please update swc

**Comment by jays1204** [comment] 2021-07-21 08:25
I am sorry for reopen but Still same error when I updated swc version.

```
 "@swc/jest": "^0.1.4",
"@swc/core": "^1.2.66",
```

And I also update swc/core version by `https://github.com/swc-project/swc/tarball/master`.
But same error. 

Thank you.

**Comment by odanado** [comment] 2021-11-27 12:50
I have confirmed that the test passes with this `.swcrc`
https://github.com/odan-sandbox/nestjs-swc-jest-sandbox/blob/main/.swcrc

**Comment by arkus7** [comment] 2022-01-21 19:01
> I have confirmed that the test passes with this `.swcrc` https://github.com/odan-sandbox/nestjs-swc-jest-sandbox/blob/main/.swcrc

I've tried to use this configuration, but I still have issues with dependency injection in tests.

```
Nest can't resolve dependencies of the MapQueueConsumer (Logger, EventBus, MapRepositoryClient, ?). Please make sure that the argument Object at index [3] is available in the MapQueueModule context.

    Potential solutions:
    - If Object is a provider, is it part of the current MapQueueModule?
    - If Object is exported from a separate @Module, is that module imported within MapQueueModule?
      @Module({
        imports: [ /* the Module containing Object */ ]
      })
```

Notice the `Object` in the message, it seems like some metadata/class names are not preserved?

![image](https://user-images.githubusercontent.com/9324869/150584319-0efc1450-6bb3-4654-b481-6b44a854a5eb.png)


This is the config in `.swcrc`
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "target": "es2017",
    "keepClassNames": true
  },
  "module": {
    "type": "commonjs",
    "noInterop": false
  }
}

```

**Comment by bmeverett** [comment] 2022-02-07 01:27
I am also experiencing an issue with NestJS, not sure if it's related or not. Here is an [example](https://github.com/bmeverett/nest-swc) where you reproduce the error.  I am getting the following error 

```
 FAIL  src/app.controller.spec.ts
  ● Test suite failed to run

    ReferenceError: Cannot access 'AppService' before initialization

      4 | @Injectable()
      5 | export class AppService {
    > 6 |   constructor(@InjectPinoLogger(AppService.name) private logger: PinoLogger) {}
        |                                 ^
      7 |   getHello(): string {
      8 |     this.logger.info('Hello world!');
      9 |     return 'Hello World!';

      at _dec2 (app.service.ts:6:33)
      at Object.<anonymous> (app.service.ts:4:14)
      at Object.<anonymous> (app.controller.ts:2:43)
```

I am injecting a logger [here](https://github.com/bmeverett/nest-swc/blob/master/src/app.service.ts#L6)
`constructor(@InjectPinoLogger(AppService.name) private logger: PinoLogger) {}`

It works if I just use `@InjectPinoLogger("AppService")` but when I try to use `AppService.name` it doesn't I get the error.

**Comment by odanado** [comment] 2022-02-07 04:29
@arkus7 
I'd like to investigate that issue more deeply.
Could you please prepare the minimum configuration to reproduce the problem?

**Comment by odanado** [comment] 2022-02-07 04:40
@bmeverett 
Probably related to do with this issue: https://github.com/swc-project/swc/issues/1866

**Comment by arkus7** [comment] 2022-02-12 07:41
> @arkus7 I'd like to investigate that issue more deeply. Could you please prepare the minimum configuration to reproduce the problem?

Sure, I'd try to find some time next week to create the minimum repository, I'll let you know in another comment when it's ready.

**Comment by jwalton** [comment] 2022-02-15 16:30
I think the `Cannot access 'AppService' before initialization` issue is the same as https://github.com/swc-project/swc/issues/3521.

**Comment by kdy1** [comment] 2022-03-12 02:54
Closing in favor of https://github.com/swc-project/swc/issues/3521

**Closed by kdy1** 2022-03-12 02:54 UTC
