### ISSUE TITLE
Mocking not working

### ISSUE THREAD

**Issue by swissspidy** [swc-project/jest#14] opened 2021-08-12 10:44 UTC
When using `@swc/jest` as described in the readme for transforms in Jest tests, I can't seem to use any mocking.

With a test like this:

```js
import got from 'got';

jest.mock('got');

describe('My Test', () => {
  // ...
});
```

I will get:

```
TypeError: _got.default.mockImplementationOnce is not a function
```

Moving the `jest.mock()` call to the top of the test file also doesn't work.

Any advice appreciated.

**Comment by unlight** [comment] 2021-08-30 20:45
Same.
By design `jest.mock()` is hoisting over import.
Also other methods `['mock', 'unmock', 'enableAutomock', 'disableAutomock', 'deepUnmock']`

https://github.com/kulshekhar/ts-jest/blob/master/src/transformers/hoist-jest.ts

**Comment by diego-aquino** [comment] 2021-11-11 14:22
> Our workaround was to declare `jest.mock` in another file and then import it in the test.

@gabberr, could you provide an example? I've tried it, but I still get the same error.

**Comment by nvh95** [comment] 2021-11-16 07:38
Hope this issue will be resolved soon. I try to switch from `babel-jest` to `@swc/jest` and this is the only remaining issue has left that blocks me from actually switch.

**Comment by gabberr** [comment] 2021-11-16 11:43
@diego-aquino here:

Create a file 'src/mocks/bunny.ts':
```js
const mockedBunny = jest.fn()
jest.mock(
  'actual/bunny/file',
  () => mockedBunny
)

export default mockedBunny
```

Inside the test where you want to mock Bunny:
```js
import 'src/mocks/bunny'

//  OR, if you want to set mock implementation in the test

import bunnyMock from 'mocks/bunny'

bunnyMock.mockImplementation(() => 'my mocked bunny')


```

**Comment by Ayc0** [comment] 2021-11-24 01:03
Try with 
```json
{
    "jsc": {
        "transform": {
            "hidden": {
                "jest": true
            }
        }
    }
}
```

I just did and it seems to be working

**Comment by Ayc0** [comment] 2021-11-24 12:13
Update: setting `hidden.jest = true` is already set by `@swc/jest`, but it wasn't applied, #44 fixes that.

At the moment of my message, the latest version of `@swc/jest` (0.2.9) doesn't include the fix yet, but I think it'll be released in the close future

**Comment by th3fallen** [comment] 2021-12-11 15:26
im actually still running into this, any work around?

**Comment by gabberr** [comment] 2021-12-15 07:05
@th3fallen have you tried https://github.com/swc-project/jest/issues/14#issuecomment-970189585 ?

@kdy1 The mentioned fix that closes this ticket was actually reverted, should this be reopened?

**Comment by Ayc0** [comment] 2021-12-15 07:34
@gabberr it was reverted indeed in swc-jest, but a commit was added to swc itself to fix the issue: see https://github.com/swc-project/jest/pull/44#issuecomment-980601069

Can you try with an up to date `swc`?

**Comment by kdy1** [comment] 2021-12-15 07:35
Ah, I forgot it.
@Ayc0  Thank you!

**Comment by Ayc0** [comment] 2021-12-15 07:37
There should be a test for jest: https://github.com/swc-project/jest/pull/46

So the mocking should work reliably now.

Can you try updating your versions of both swc and swc-jest to see if it is really broken? (And also can you send a way to replicate the bug? So that we can add more tests)

**Comment by MhMadHamster** [comment] 2021-12-15 18:41
> There should be a test for jest's mocking mechanism: #46 So it should work now.
> 
> Can you try updating your versions of both swc and swc-jest to see if it is still broken for you? (And also can you send a way to replicate the bug? So that we can add more tests)

It still doesn't work if you want to mock implementation and pass mock function as the desired export for the module that you're trying to mock. See: https://github.com/MhMadHamster/swc-jest-mock-bug/tree/master
You can get around it tho by doing something like this:
```JavaScript
const mockedImpl = jest.fn();

jest.mock("./to-be-mocked", () => ({
  fnOne: () => mockedImpl(),
}));

describe("", () => {
  it("fnOne test", () => {
    callFnOne()
    expect(mockedImpl).toBeCalledTimes(1);
  });
});
```

**Comment by Ayc0** [comment] 2021-12-15 23:44
@MhMadHamster I don't think this is related to swc at all: you cannot use `mockedImpl` here as it's a top level variable. But `jest.mock` are self contained.

I forked your repo here: https://github.com/Ayc0/swc-jest-mock-bug

and as you can see, you can see, the test can pass by tweaking them a bit:

![image](https://user-images.githubusercontent.com/22725671/146281786-80e8baf4-7f58-4db6-b66f-92f8d346b247.png)

Instead of doing:

```js

   
import { callFnOne, callFnTwo } from "./index";

const mockedImpl = jest.fn();

jest.mock("./to-be-mocked", () => ({
  fnOne: () => "mocked",
  fnTwo: mockedImpl, // cannot reference global variable
}));

describe("wrong test", () => {
  it("fnOne test", () => {
    expect(callFnOne()).toBe("mocked");
  });

  it("fnTwo test", () => {
    callFnTwo();
    expect(mockedImpl).toBeCalledTimes(1);
  });
});
```

You should do 

```js
import { callFnOne, callFnTwo } from "./index";
import { fnTwo } from "./to-be-mocked";

jest.mock("./to-be-mocked", () => ({
  fnOne: () => "mocked",
  fnTwo: jest.fn(), // doesn't depend on global var
}));

describe("correct test", () => {
  it("fnOne test", () => {
    expect(callFnOne()).toBe("mocked");
  });

  it("fnTwo test", () => {
    callFnTwo();
    expect(fnTwo).toBeCalledTimes(1); // use fnTwo directly
  });
});
```


This isn't related to SWC and you'd have the same issue with Babel. You can find here a section related to that in Jest's doc: https://jestjs.io/docs/es6-class-mocks#calling-jestmock-with-the-module-factory-parameter


![image](https://user-images.githubusercontent.com/22725671/146282090-60de165d-5094-4906-9372-9c922d368b24.png)

**Comment by Ayc0** [comment] 2021-12-16 00:05
@MhMadHamster I don't think this is related to swc at all: you cannot use `mockedImpl` here as it's a top level variable: `jest.mock` must be self contained.

I forked your repo here: https://github.com/Ayc0/swc-jest-mock-bug if you want to give it a try.


I think this is related to: https://jestjs.io/docs/es6-class-mocks#calling-jestmock-with-the-module-factory-parameter

![image](https://user-images.githubusercontent.com/22725671/146282090-60de165d-5094-4906-9372-9c922d368b24.png)


In the fork, you can see that I disabled swc and here are my results without swc:
![image](https://user-images.githubusercontent.com/22725671/146283871-7f850409-0c92-4215-9825-b1c67dbe52e5.png)


and here with swc:
![image](https://user-images.githubusercontent.com/22725671/146283912-93a16701-92ca-43b3-981a-eebc53db8678.png)


There seems to be a difference with the hoisting of `mock*` variables, but your example still failed without SWC.

The `mock*` could be investigated indeed (what do you think @kdy1?)

**Comment by kdy1** [comment] 2021-12-16 06:25
I think the exception with swc should match the exception without swc.
Seems like a different issue though.

**Comment by Ayc0** [comment] 2021-12-16 06:38
I agree, I'll open another issue

**Comment by Ayc0** [comment] 2021-12-16 11:03
I opened https://github.com/swc-project/jest/issues/59

**Comment by th3fallen** [comment] 2021-12-16 14:14
in my case the mocking failure is from this...

```import { getUserId } from 'shared/auth';

getUserId.mockReturnValue('1');

describe("", () => {
  it("getUserId test", () => {
    
    expect(getUserId).toBe(1);
  });
});```

**Comment by MhMadHamster** [comment] 2021-12-17 17:17
> I think this is related to: https://jestjs.io/docs/es6-class-mocks#calling-jestmock-with-the-module-factory-parameter

I discovered that i had this issue because I was using `ts-jest` before, and apparently it allows using local variables in the mock factory, hence i thought issue was in swc 😕

**Comment by Ayc0** [comment] 2021-12-17 17:21
I think `ts-jest` is using `tsc` which usually changes the variables from `const/let` to `var` (and `var` variables are hoisted to the top of the file).

But this is a guess.

**Comment by kdy1** [comment] 2022-01-27 12:09
Is this still an issue?

**Comment by th3fallen** [comment] 2022-01-28 16:03
yes

**Comment by Ayc0** [comment] 2022-02-03 18:22
@kylemh as mentioned above, I don't think that this code would work either with just jest (and babel)

`jest.mock` isn't meant to be used with code defined out of its scope

instead you should do:

```js
jest.mock('connected-react-router', () => {
  const replaceMock = jest.fn(() => ({ type: '' }));
  return {
    replace: replaceMock,
  };
});
```

**Comment by kylemh** [comment] 2022-02-03 18:28
so you're suggesting that ts-jest is making this work?

**Comment by Ayc0** [comment] 2022-02-03 18:33
Maybe, I think it's related to https://github.com/swc-project/jest/issues/14#issuecomment-996890800.

But according to jest's doc, your code isn't supposed to work.

**Comment by Ayc0** [comment] 2022-02-03 18:35
Btw, when I inject your code in [babel repl](https://babeljs.io/repl#?browsers=chrome%2080&build=&builtIns=usage&corejs=3.6&spec=false&loose=false&code_lz=MYewdgzgLgBATgUwA4BsCGwEFkTANYwC8MAVgtAHQBmYAFLQJREB8MtA3jFAJ5IIBcMAORCYAXwYMA3ACgylALa48tIaDBgEwKAgAmAWkQYohkAFcdcIQBo2TQqw4yY8ZOkyDEqDNmXWZEtJAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=&version=7.17.1&externalPlugins=babel-plugin-jest-hoist%4027.4.0&assumptions=%7B%7D) with the plugin `jest-hoist`, it throws this error:

![image](https://user-images.githubusercontent.com/22725671/152406849-dcc64dab-e6b7-4802-b99d-78ae3b940a3b.png)

**Comment by kylemh** [comment] 2022-02-03 21:01
Sorry. To be clear, what I shared was just a snippet of the test code and I didn't share any source code.

I'm calling `jest.mock()` at the top-level scope of the test file and the test file is importing and testing a component that leverages `connected-react-router`.

**Comment by robertwt7** [comment] 2022-03-22 11:37
omg I was scratching my head the whole day. Lucky I saw this issue!

**Comment by bard** [comment] 2022-09-06 20:33
For posterity, if this is giving you trouble:

```javascript
const mockReplace = jest.fn(() => ({ type: '' }));
jest.mock('connected-react-router', () => ({
  replace: mockReplace,
}));
```

Try converting it to:

```javascript
const mockReplace = jest.fn(() => ({ type: '' }));
jest.mock('connected-react-router', () => ({
  replace: (...args) => mockReplace(...args),
}));
```

**Comment by aluzed** [comment] 2022-12-28 10:26
Have you check for any esModuleInterop bug with swc ? 

We noticed that swc ts compilation may encounter some problems if you use imports like `import * as moment from 'moment'` we replaced it by a simple `const moment = require('moment')` to solve the it.

**Comment by timbicker** [comment] 2023-01-10 16:45
@Ayc0 it is still failing. I created a repo to reproduce the bug https://github.com/timbicker/swc-jest-mock-bug/tree/main with a very minimal example.

app.js
```
export function app() {
  return "Hi"
}
```

app.test.js
```
import {jest} from "@jest/globals"

jest.mock("./app", () => ({
  app: jest.fn(() => "Bye")
}))
import {app} from "./app"


test("Test", () => {
  expect(app()).toBe("Bye")
})
```

**Comment by Ayc0** [comment] 2023-01-16 11:53
> @Ayc0 it is still failing. I created a repo to reproduce the bug https://github.com/timbicker/swc-jest-mock-bug/tree/main with a very minimal example.

This may be an issue with the `jest` import ([REPL](https://play.swc.rs/?version=1.3.26&code=H4sIAAAAAAAAAz2NQQrCQAxF9zlFyCoBme4FRXoGL1BLKtWOGdosKqV3d8ZqN4H%2Fef%2Blj8lGx%2BWhk6%2FYjRaRLiVU98FuzTARQIkhWvtkClWTEh2QBU9n5AUQc3HEL9K9eOupfisJrCIA%2Fe9Bxv7%2BTQLgecR0zXc3FqHOSVvnzLBIcKuVdyHAB0Dsf2OxAAAA&config=H4sIAAAAAAAAA0WOSwrDMAxE76J1Fm2hXeQOPYSxldQh%2FqBxoCbk7rWCS3Yzo5mHdlpgadwpGwGLKtRYzJdGKjUzrPhcaKCCFk1mBR%2FNiImYkgTtf7xzHFUtjEJjkY0PLRmZuXliPG73Z2OsKYE7ZaDgo5%2Bq7mwKWRi4TibO67%2BprJDcpsF%2BPnUyX3RcjL7zePfi%2BcQPCpUuMt0AAAA%3D)):

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/22725671/212672041-c7ef8d44-03df-41fc-87dd-1d672a402dd2.png">

As we can see here: `jest.mock` get hoisted, but not `import {jest}`

You may want to open an issue on the SWC repo as the hoisting is done by swc directly when this transform is enabled:

```json
"transform": {
  "hidden": {
    "jest": true
  }
}
```

**Comment by Kampfmoehre** [comment] 2023-02-21 09:48
I also have the problem for some time now and can't find a way to fix it.

You can see an example [here](https://github.com/droidsolutions/semantic-release-nuget/actions/runs/4231168642/jobs/7349352213#step:5:143) - you can find the corresponding teste [here](https://github.com/droidsolutions/semantic-release-nuget/blob/5a52847560fd8ec22dbf4768702f0e8f0fde5b71/test/publish.test.ts#L104).

I try to mock execa for a Semantic Release plugin - which previously worked - just by using `jest.mock("execa)`. But with `@swc/jest` the import is not mocked but instead imported directly.

I tried the hidden/jest config but I am unsure where exactly to put it, I tried setting it in pckage.json like this but to no avail:
```json
    "transform": {
      "^.+\\.(t|j)sx?$": [
        "@swc-node/jest",
        {
          "dynamicImport": true,
          "jsc": {
            "transform": {
              "hidden": {
                "jest": true
              }
            }
          }
        }
      ]
    }
```

Is there anything else I can try to make it work again?

**Comment by Kampfmoehre** [comment] 2023-02-22 09:04
I am aware but the project is not using ESM yet. I know the execa module is using ESM, that is way we stick to version 5.1.1 for now. But npm ls shows that some dev dependencies have a higher (ESM) version of execa installed, so I am not sure if this can interfere.
The tests are written in typescript, that is why we use import * from syntax there. Or am I missing something?

**Comment by kdy1** [comment] 2023-02-22 09:06
`import * as foo from 'foo'` is the syntax for ESM.

**Comment by kdy1** [comment] 2023-02-22 09:06
I know - `tsc` miscompiles them, but I'm not going to follow the wrong behavior of `tsc`

**Comment by Kampfmoehre** [comment] 2023-02-22 09:10
I am a little bit confused now.
The test is written in TypeScript using the default import from syntax but when jest runs the test should have been transpiled to CommonJS with a require syntax. When I manually transpile the code it is emitted as such and until now I assumed SWC would do exactly the same before handing the code to jest?
The tests worked for some time until a recent version of swc. Or am I wrong here and SWC is producing ESM code now?

**Comment by kdy1** [comment] 2023-02-22 09:23
You used the syntax for ESM, so it should follow semantics of ESM

**Comment by pm0u** [comment] 2023-03-08 20:20
I am having trouble overriding an import in a file that is being tested, I'm unsure if this issue is related...

```ts
// items/valid-items.ts

export const validItems = ["item1", "item2"]
```

```ts
// item-validator.ts
import { validItems } from './items/valid-items'

export const isValidItem = (item: string) => {
  return validItems.includes(item)
}
```

```ts
// item-validator.test.ts
import { isValidItem } from './item-validator'
import { jest, test, expect } from '@jest/globals'

jest.mock('./items/valid-items', () => ({
    validItems: ["item3", "item4"]
  })
  
  test("Items are valid", () => {
    const isValid = isValidItem("item3")
    // test fails
    expect(isValid).toBe(true)
  })
  ```

**Comment by Wazbat** [comment] 2023-03-16 21:02
I'm also running into this same issue. I'm trying to use `jest.mock('./service');` however no matter where in the file I put the mock call, jest continues to import the original file

**Closed** 2023-03-17 00:17 UTC

**Comment by Wazbat** [comment] 2023-03-23 09:05
I see the issue is closed, was this fixed? In what version?

**Comment by Ayc0** [comment] 2023-03-23 18:42
There seems to indeed be an issue with the mocking with CJS: if we build in ESM, it hoist properly the `jest.mock` ([REPL](https://play.swc.rs/?version=1.3.42&code=H4sIAAAAAAAAA1WPMQ%2BCMBCF9%2F6Ky01tgmWXaFwcXHU0DkhOUi1UypEQlf9uCxHDcsPd%2B967Z6qn8wxvuFPLCfA4qX9SwTDAzbsKcBdvaWndNbctZsL8GMNUtUcqqZ%2B1Oh2XKx%2B3QVu4unWWtHWlRE9NZzyhyoSInrpyxUP%2BGExAKths4S0AFlyURQjAE3e%2BHhUwxa%2FhjNf8FWBsuh4vSTgNmRhiRmwj8TB%2FuUiYSsp%2FB6XZndibgvdNl1uZyuD7CaYqLdXk%2BAWMq%2Ft1LgEAAA%3D%3D&config=H4sIAAAAAAAAA21QzQ6CMAy%2B8xSkZw%2FqwRjfwYdYoOAM%2B0lbEgnh3dnGhph4Wdrvr%2B3mqq7hzQ086jmUofGKGGnvA8KTFfUJCMjkkRvSXuBUWOFIdWpgTNCyMSCKepToQr6eL%2FfsgME5xuLImNFWd9NxZuOMJ2T%2BFUapsv2A%2FyeSstw5Msegl25btAck3oscFxMaMYNLVd4UBsa1Y5qSPyUevp1yg6%2BobL1vCJqfxZnSlxVPeQE1YAEAAA%3D%3D)):

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/22725671/227315975-6601c1d9-2e6f-424d-9b18-62382f6472a0.png">


But not with CJS (it gets added after the requires) ([REPL](https://play.swc.rs/?version=1.3.42&code=H4sIAAAAAAAAA1WPMQ%2BCMBCF9%2F6Ky01tgmWXaFwcXHU0DkhOUi1UypEQlf9uCxHDcsPd%2B967Z6qn8wxvuFPLCfA4qX9SwTDAzbsKcBdvaWndNbctZsL8GMNUtUcqqZ%2B1Oh2XKx%2B3QVu4unWWtHWlRE9NZzyhyoSInrpyxUP%2BGExAKths4S0AFlyURQjAE3e%2BHhUwxa%2FhjNf8FWBsuh4vSTgNmRhiRmwj8TB%2FuUiYSsp%2FB6XZndibgvdNl1uZyuD7CaYqLdXk%2BAWMq%2Ft1LgEAAA%3D%3D&config=H4sIAAAAAAAAA21QSQ7CMAy89xWVzxyAE%2BIPPCJq3ZKqWWSnElWVvxOHpBSJS2TPeDzjbE3bwsQd3Nstlanxihhp7xPCqw3qlRAIq0fuSPsAp8oGFmpQM2OG4oeBoGjEICrk6%2FlyKwqYnWOsioIZbfWwHj07Zzwh8%2B%2BgjCo7zvjfkZTlwZE5Lnrqvkd7QOReZAkWaMECxqa%2BeRkY1y%2FZpXyKHC6npFjG2YnhO1mj7zFB86PKs0V8Azfsl1BlAQAA)):
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/22725671/227316248-da1b0238-9b8c-48bc-a1fb-d8f9c73d532f.png">


We should create another issue

**Comment by Smrtnyk** [comment] 2023-03-23 18:45
> There seems to indeed be an issue with the mocking with CJS: if we build in ESM, it hoist properly the `jest.mock` ([REPL](https://play.swc.rs/?version=1.3.42&code=H4sIAAAAAAAAA1WPMQ%2BCMBCF9%2F6Ky01tgmWXaFwcXHU0DkhOUi1UypEQlf9uCxHDcsPd%2B967Z6qn8wxvuFPLCfA4qX9SwTDAzbsKcBdvaWndNbctZsL8GMNUtUcqqZ%2B1Oh2XKx%2B3QVu4unWWtHWlRE9NZzyhyoSInrpyxUP%2BGExAKths4S0AFlyURQjAE3e%2BHhUwxa%2FhjNf8FWBsuh4vSTgNmRhiRmwj8TB%2FuUiYSsp%2FB6XZndibgvdNl1uZyuD7CaYqLdXk%2BAWMq%2Ft1LgEAAA%3D%3D&config=H4sIAAAAAAAAA21QzQ6CMAy%2B8xSkZw%2FqwRjfwYdYoOAM%2B0lbEgnh3dnGhph4Wdrvr%2B3mqq7hzQ086jmUofGKGGnvA8KTFfUJCMjkkRvSXuBUWOFIdWpgTNCyMSCKepToQr6eL%2FfsgME5xuLImNFWd9NxZuOMJ2T%2BFUapsv2A%2FyeSstw5Msegl25btAck3oscFxMaMYNLVd4UBsa1Y5qSPyUevp1yg6%2BobL1vCJqfxZnSlxVPeQE1YAEAAA%3D%3D)):
> 
> <img alt="image" width="1496" src="https://user-images.githubusercontent.com/22725671/227315975-6601c1d9-2e6f-424d-9b18-62382f6472a0.png">
> 
> But not with CJS (it gets added after the requires) ([REPL](https://play.swc.rs/?version=1.3.42&code=H4sIAAAAAAAAA1WPMQ%2BCMBCF9%2F6Ky01tgmWXaFwcXHU0DkhOUi1UypEQlf9uCxHDcsPd%2B967Z6qn8wxvuFPLCfA4qX9SwTDAzbsKcBdvaWndNbctZsL8GMNUtUcqqZ%2B1Oh2XKx%2B3QVu4unWWtHWlRE9NZzyhyoSInrpyxUP%2BGExAKths4S0AFlyURQjAE3e%2BHhUwxa%2FhjNf8FWBsuh4vSTgNmRhiRmwj8TB%2FuUiYSsp%2FB6XZndibgvdNl1uZyuD7CaYqLdXk%2BAWMq%2Ft1LgEAAA%3D%3D&config=H4sIAAAAAAAAA21QSQ7CMAy89xWVzxyAE%2BIPPCJq3ZKqWWSnElWVvxOHpBSJS2TPeDzjbE3bwsQd3Nstlanxihhp7xPCqw3qlRAIq0fuSPsAp8oGFmpQM2OG4oeBoGjEICrk6%2FlyKwqYnWOsioIZbfWwHj07Zzwh8%2B%2BgjCo7zvjfkZTlwZE5Lnrqvkd7QOReZAkWaMECxqa%2BeRkY1y%2FZpXyKHC6npFjG2YnhO1mj7zFB86PKs0V8Azfsl1BlAQAA)): <img alt="image" width="1511" src="https://user-images.githubusercontent.com/22725671/227316248-da1b0238-9b8c-48bc-a1fb-d8f9c73d532f.png">
> 
> But the test works again if we remove the imports from `@jest/globals` ([REPL](https://play.swc.rs/?version=1.3.42&code=H4sIAAAAAAAAA1WPMQ%2BCMBCF9%2F6Ky01tgrBLNC4OrjoaByAnqRYr5UiIyH%2B3hYBhffe99%2B7p6m0dQw9MDUdA3ZsKhgHuzlaAh4dXk9LYPDMNpkLPtGaqmjOV1C1snIzixgXVs4V9NdZQbGwp0VHdakeoUiFCZlzZ4ilnD0YgFez20AuAlS9gwQTgiFv3GgmY6rdwxTz7eDPWbYe3yJ%2BGVAyhI6yReFq%2BXDVMI%2BV%2Fg4rZXtjpgo91mxmZSJ%2F79aEqKdWU%2BAOfHgQCKAEAAA%3D%3D&config=H4sIAAAAAAAAA21QSQ7CMAy89xWVzxyAE%2BIPPCJq3ZKqWWSnElWVvxOHpBSJS2TPeDzjbE3bwsQd3Nstlanxihhp7xPCqw3qlRAIq0fuSPsAp8oGFmpQM2OG4oeBoGjEICrk6%2FlyKwqYnWOsioIZbfWwHj07Zzwh8%2B%2BgjCo7zvjfkZTlwZE5Lnrqvkd7QOReZAkWaMECxqa%2BeRkY1y%2FZpXyKHC6npFjG2YnhO1mj7zFB86PKs0V8Azfsl1BlAQAA)):
> 
> <img alt="image" width="1235" src="https://user-images.githubusercontent.com/22725671/227316677-8255c3cb-1102-470d-9bac-784f837c83b6.png">
> 
> We should create another issue as this seems to be only related to `@jest/globals`

are you sure it is not this https://github.com/swc-project/swc/issues/5205?

**Comment by Ayc0** [comment] 2023-03-23 18:47
In your case @pm0u, you can just drop the imports on `@jest/globals` and it should work great:
- run `yarn add -D @types/jest` to have the global types working with TS
- drop the package `@jest/globals` & remove the imports

<img width="585" alt="image" src="https://user-images.githubusercontent.com/22725671/227317409-156afa62-e217-44e1-b74e-82feca9e7c28.png">

**Comment by Ayc0** [comment] 2023-03-23 18:47
> are you sure it is not this https://github.com/swc-project/swc/issues/5205?

You don't seem to be running ESM code in this example. Also to my knowledge, Jest isn't compatible with mocks with ESM

**Comment by Smrtnyk** [comment] 2023-03-23 18:49
but he is using esm syntax, and swc treats it strictly as esm

**Comment by pm0u** [comment] 2023-03-23 18:52
The use case I have is this is a script that is ultimately run using `node -r @swc-node/register file.ts`

I just want to be able to write a test in typescript and have predictable behavior with the environment it is run in, I have no idea what that above command actually compiles to.

Dropping the `@jest/globals` could work for my use case, but I don't love just having `jest` as a global in every file in the project as this isn't really true. As a "workaround", I suppose it's acceptable.

**Comment by pm0u** [comment] 2023-03-23 18:59
I see, thanks for the explanation and solution! this is obviously a complex problem and I appreciate everyone taking the time to sort it out correctly and in line with established standards. I think we will be able to work with the provided solutions. thanks again.

**Comment by tangentlin** [comment] 2023-04-10 16:46
In my case, import from `@jest/globals` was the culprit, by removing it the tests run fine.

**Comment by kkirby** [comment] 2024-02-20 15:19
I switched to Vitest after I couldn't get jest working.

**Comment by leonardotc** [comment] 2024-06-07 07:41
Just to add. The above solutions worked for me (using the factory). The thing is that the variables in that context retain their original values so if you need to access their "mocked versions" you will need to use `jest.requireMock`. 
```
jest.mock('./utils', () => ({
  ...jest.requireActual('./utils'),
  createTransport: jest.fn(() => ({ send: handleWithMock }))
}))
```
```
it('should do something else', async () => {
      const mockedUtils = jest.requireMock('./utils')
      mockedUtils.createTransport.mockImplementationOnce(() => ({
        send: overridenHandleWithMock
      }))
})
```
Idk if it will help anyone but it took me a while to figure it out.

**Comment by Sammaye** [comment] 2024-12-07 22:16
I am still getting this on the latest version of SWC, removing the ject globals import seemed to do the trick

**Comment by Sammaye** [comment] 2024-12-07 22:32
Also simply weirdly editing it to remove only certain imports works i.e.:

    import { afterAll, beforeAll, describe, expect, it, test } from '@jest/globals';

Is ok but 

    import { afterAll, beforeAll, describe, expect, it, jest, test } from '@jest/globals';

Is not
