### ISSUE TITLE
Incorrect branch coverage

### ISSUE THREAD

**Issue by sscode02** [swc-project/jest#84] opened 2022-03-11 06:29 UTC
Hi

When I use swc/ject I get a wrong branch coverage and wrong highlighting, but not when I use ts-jest
I have created repository with complete reproduction at [https://github.com/sscode02/nest-swc](https://github.com/sscode02/nest-swc)
To run test execute npm run test:e2e:swc

Could you please tell me what should I do?

Thank you

**Comment by kdy1** [comment] 2022-03-11 06:30
Closing as duplicate of https://github.com/swc-project/swc/issues/3854

**Closed by kdy1** 2022-03-11 06:30 UTC
