### ISSUE TITLE
Cannot generate a coverage report

### ISSUE THREAD

**Issue by leonardparisi** [swc-project/jest#65] opened 2022-01-08 14:06 UTC
I don't know if this is an issue specifically with `@swc/jest`, but I tried the suggestions in this [StackOverflow ](https://stackoverflow.com/questions/57451028/jest-finds-tests-but-doesnt-collect-coverage) question and they made no difference. Here is my `jest.config.js`:
```js
module.exports = {
  'roots': ['<rootDir>/../src'],
  'moduleDirectories': ['node_modules', 'src'],
  'setupFilesAfterEnv': ['<rootDir>/setup-tests.js'],
  'coverageDirectory': '<rootDir>/../coverage',
  'verbose': true,
  'collectCoverage': true,
  'transform': {
    '^.+\\.(t|j)sx?$': [
      '@swc/jest',
      {
        'jsc': {
          target: 'es2021',
        },
        'sourceMaps': true,
      },
    ],
  },
  'collectCoverageFrom': [
    '<rootDir>/../src/**.{ts,js,tsx,jsx}',
    '!**/node_modules/**',
  ],
}
```

My file structure looks like: 
```js
.
├── coverage
├── jest
│   ├── jest.config.js
│   ├── setup-tests.js
├── src/
├── tsconfig.json
```

The output looks like this:
```sh
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------

Test Suites: 11 passed, 11 total
Tests:       25 passed, 25 total
Snapshots:   0 total
Time:        1.307 s
Ran all test suites.
```

**Comment by kdy1** [comment] 2022-01-12 08:28
I think it can be a problem of a sourcemap.

**Comment by kdy1** [comment] 2022-02-03 07:04
I think it may work if you remove `sourceMaps: true`. Can you try it?

**Comment by kalvin807** [comment] 2022-02-08 09:34
I was having a similar problem,
I think the fix is you need a correct collectCoverageFrom glob like this
```
  collectCoverageFrom: [
    "src/**/*.{ts,js,tsx,jsx}",
    "!**/node_modules/",
  ],
```
yours is `**.{ts...}` while it should be single asterisk `**/*.{ts...}` < recurive each folder and each file that matches the extensions list in src folder

**Comment by kdy1** [comment] 2022-02-24 07:21
Closing as duplicate of #21

**Closed by kdy1** 2022-02-24 07:21 UTC
